language: java
jdk:
  - oraclejdk8
 
script: mvn test -f ./travis-ci-pom.xml > RESULT-h000002.html
cache:
  directories:
  - $HOME/.m2

before_script:
  - rm -rf .git*
  - git config --global user.name "wruiwr"
  - git config --global user.email "wruiwr86@gmail.com"
  - git clone https://wruiwr:$GITHUB_TOKEN_PRIVATE@github.com/wruiwr/travis-results.git

after_script:
  - cp RESULT-h000002.html ./travis-results/
  - cd travis-results
  - ls -lat
  - git status -s
  - git add RESULT-h000002.html #-A
  - git status -s
  - git commit -m "update building result"
  - git push
