language: java
jdk:
  - oraclejdk8
  
script: mvn test -f ./travis-ci-pom.xml > RESULT.html
cache:
  directories:
  - $HOME/.m2
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
