language: java
jdk:
  - oraclejdk8

before_script:
  - git config --global user.name "wruiwr"
  - git config --global user.email "wruiwr86@gmail.com"
  - rm -rf travis-building-results
  - mkdir travis-building-results

script: mvn test -f ./travis-ci-pom.xml > ./travis-building-results/BUILDING_RESULT.html
cache:
  directories:
  - $HOME/.m2
  
after_script:
  - ls -lat
  - git checkout master
  - git status -s
  - git add -A
  - git status -s
  - git commit -m "update building result [ci skip]"
  - git push --force --quiet https://wruiwr:$GITHUB_TOKEN@github.com/dat100hib/jpl0-oppgave3-h000001 master

